[game]
server_id = 1
host = "127.0.0.1"
port = 8001

[redis]
host = "127.0.0.1"
port = 6379
password = ""
db = 0

[mysql]
host = "127.0.0.1"
port = 3306
dbname = "nano_learn"
password = "123456"
username = "root"
charset = "utf8mb4"
max_idle_conns = 20
max_open_conns = 15
show_sql = false
# 0-debug, 1-info, 2-warning, 3-error, 4-off, 5-unknow
log_level = 0